### ISSUE TITLE
Something's wrong with the way float is clearing on the project grid

### ISSUE THREAD

**Issue by mattstauffer** [StayWokeOrg/staywokeorg.github.io#4]
![image](https://cloud.githubusercontent.com/assets/151829/21826691/79b1e8d0-d756-11e6-853e-d877e99efc7f.png)

This happens some times but not always, depending on the amount of content in each

**Comment by jendowns** [comment]
Thanks for submitting this issue, Matt! I'll take a look.

- Jen

**Comment by jendowns** [comment]
Hey Matt,

I reorganized the `col-*` divs so that there are two divs per `row` container. Previously, all `col-*` divs in that section were in the same `row` container, so the floating columns weren't collapsing in a pretty way as you narrowed your browser (as demonstrated in your screenshot).

My changes have adjusted the look slightly but I think it's a good start, since it keeps everything neat and tidy. Please note that there is an "offset" on either side of each row, but we can also tweak that if we find the spacing is too much.

Please let me know if you have any questions or comments! I'll wait to see your feedback before I close this one out.

Best,
Jen

**Comment by mattstauffer** [comment]
:+1: Nice chance! Thanks!
